#!/bin/bash
# ============================================
# Magpie AI - Local Docker Setup Script
# ============================================
# Sets up complete local environment with Docker Compose

set -euo pipefail

echo "=========================================="
echo "MAGPIE AI - LOCAL DOCKER SETUP"
echo "=========================================="

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Step 1: Check prerequisites
log_info "Checking prerequisites..."

if ! command -v docker &> /dev/null; then
    log_error "Docker not found. Please install Docker Desktop"
    exit 1
fi

if ! docker info &> /dev/null; then
    log_error "Docker is not running. Please start Docker Desktop"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    log_error "Docker Compose plugin not found. Please update Docker Desktop"
    exit 1
fi

log_success "Prerequisites check passed"

# Step 2: Stop any existing containers
log_info "Cleaning up existing containers..."

if docker compose ps -q &> /dev/null; then
    log_info "Stopping and removing existing containers and volumes..."
    docker compose down -v 2>/dev/null || true
    log_success "Existing containers cleaned up"
fi

# Step 3: Generate .env file
log_info "Generating environment configuration..."

if [ -f .env ]; then
    log_warning ".env file already exists. Backing up to .env.backup"
    cp .env .env.backup
fi

# Generate secure secrets
POSTGRES_PASSWORD=$(openssl rand -hex 16)
SECRET_KEY=$(openssl rand -hex 32)
JWT_SECRET_KEY=$(openssl rand -hex 32)
ADMIN_PASSWORD=$(openssl rand -base64 16 | tr -d '\n' | head -c 20)
ADMIN_EMAIL="admin@magpie.local"

# Create .env file
cat > .env << EOF
# ==============================================
# Magpie AI - Local Docker Environment
# ==============================================
# Auto-generated by setup.sh on $(date)

# ----------------------------------------------
# Database Configuration
# ----------------------------------------------
POSTGRES_DB=magpie
POSTGRES_USER=magpie
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# ----------------------------------------------
# Security & Authentication
# ----------------------------------------------
SECRET_KEY=$SECRET_KEY
JWT_SECRET_KEY=$JWT_SECRET_KEY

# Admin user credentials
ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_PASSWORD=$ADMIN_PASSWORD

# ----------------------------------------------
# CORS Configuration
# ----------------------------------------------
ALLOWED_ORIGINS=["http://localhost:3000","http://localhost:8000"]

# ----------------------------------------------
# LLM Configuration
# ----------------------------------------------
VLLM_URL=http://llm:1234

# ----------------------------------------------
# Redis Configuration
# ----------------------------------------------
REDIS_URL=redis://redis:6379/0
EOF

log_success ".env file created with secure credentials"

# Step 4: Check for GPU support
log_info "Checking GPU support..."

HAS_GPU=false
if command -v nvidia-smi &> /dev/null; then
    if nvidia-smi &> /dev/null; then
        HAS_GPU=true
        log_success "NVIDIA GPU detected"
    fi
fi

if [ "$HAS_GPU" = false ]; then
    log_warning "No NVIDIA GPU detected - LLM service will be skipped"
    log_warning "You can still use the API with external LLM endpoints"
fi

# Step 5: Start services
log_info "Starting Docker services..."

if [ "$HAS_GPU" = true ]; then
    # Start all services including GPU-enabled LLM
    log_info "Starting all services (including LLM with GPU)..."
    docker compose up -d
else
    # Start services without LLM
    log_info "Starting services (without LLM)..."
    docker compose up -d --build postgres redis api worker nginx
fi

log_success "Docker services started"

# Step 6: Wait for services to be healthy
log_info "Waiting for services to be ready..."

# Wait up to 60 seconds for API to be healthy
for i in {1..30}; do
    if curl -f http://localhost/health &> /dev/null; then
        log_success "API is responding"
        break
    fi
    
    if [ $i -eq 30 ]; then
        log_warning "API took longer than expected to start, but may still be initializing"
        log_info "Check status with: docker compose ps"
        log_info "View logs with: docker compose logs api"
    fi
    
    echo -n "."
    sleep 2
done
echo ""

# Step 7: Create admin user
log_info "Creating admin user..."

# Wait a bit more for database migrations
sleep 5

docker compose exec -T api python -m scripts.setup_admin || {
    log_warning "Admin user creation might have failed. Check logs if needed."
}

log_success "Admin user setup completed"

# Step 8: Show summary
echo ""
log_success "🎉 Setup Complete!"
echo ""
log_info "📍 Services Running:"
docker compose ps
echo ""
log_info "🔗 Access Points:"
echo "   API Docs:    http://localhost/docs"
echo "   Health:      http://localhost/health"
echo "   Direct API:  http://localhost:8000"
echo ""
log_info "👤 Admin Credentials:"
echo "   Email:       $ADMIN_EMAIL"
echo "   Password:    $ADMIN_PASSWORD"
echo ""
log_info "📊 View Logs:"
echo "   All services:  docker compose logs -f"
echo "   API only:      docker compose logs -f api"
echo "   LLM only:      docker compose logs -f llm"
echo ""
log_info "🛠️ Useful Commands:"
echo "   Stop services:     docker compose stop"
echo "   Start services:    docker compose start"
echo "   Restart service:   docker compose restart api"
echo "   Shell access:      docker compose exec api bash"
echo "   View DB:           docker compose exec postgres psql -U magpie -d magpie"
echo ""
log_info "🛑 Teardown:"
echo "   Stop & remove:     docker compose down"
echo "   Remove volumes:    docker compose down -v"
echo ""

if [ "$HAS_GPU" = false ]; then
    log_warning "⚠️  LLM service not running (no GPU)"
    log_warning "To use content moderation/PII detection:"
    log_warning "1. Update SDK to use external API endpoint"
    log_warning "2. Or run on a machine with NVIDIA GPU"
fi

log_success "Credentials saved to: .env"
echo ""
